--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

-- Started on 2025-06-25 00:05:06

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 234 (class 1259 OID 24708)
-- Name: tb_avaliacao; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_avaliacao (
    id bigint NOT NULL,
    data character varying(255),
    nota real,
    aluno_id bigint,
    monitoria_id bigint
);


ALTER TABLE public.tb_avaliacao OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 24707)
-- Name: tb_avaliacao_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tb_avaliacao ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_avaliacao_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 24618)
-- Name: tb_cargo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_cargo (
    id bigint NOT NULL,
    contrato_trabalho character varying(255) NOT NULL,
    carga_horaria real NOT NULL,
    departamento character varying(255) NOT NULL,
    descricao_cargo character varying(255) NOT NULL,
    nome_cargo character varying(255) NOT NULL
);


ALTER TABLE public.tb_cargo OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 24667)
-- Name: tb_cargo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.tb_cargo_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.tb_cargo_seq OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 24714)
-- Name: tb_certificado; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_certificado (
    id bigint NOT NULL,
    descricao character varying(255),
    duracao character varying(255),
    titulo character varying(255),
    data character varying(255),
    participante_id bigint
);


ALTER TABLE public.tb_certificado OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 24713)
-- Name: tb_certificado_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tb_certificado ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_certificado_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 24625)
-- Name: tb_contrato_trabalho; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_contrato_trabalho (
    id bigint NOT NULL,
    data_fimm character varying(255) NOT NULL,
    data_inicio character varying(255) NOT NULL,
    salario_base real NOT NULL,
    tipo_contrato character varying(255) NOT NULL
);


ALTER TABLE public.tb_contrato_trabalho OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 24668)
-- Name: tb_contrato_trabalho_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.tb_contrato_trabalho_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.tb_contrato_trabalho_seq OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 24632)
-- Name: tb_departamento; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_departamento (
    id bigint NOT NULL,
    nome_departamento character varying(255) NOT NULL,
    ramal character varying(255) NOT NULL,
    responsavel character varying(255) NOT NULL
);


ALTER TABLE public.tb_departamento OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 24669)
-- Name: tb_departamento_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.tb_departamento_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.tb_departamento_seq OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 24722)
-- Name: tb_evento; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_evento (
    id bigint NOT NULL,
    data character varying(255),
    descricao character varying(255),
    local character varying(255),
    titulo character varying(255) NOT NULL
);


ALTER TABLE public.tb_evento OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 24721)
-- Name: tb_evento_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tb_evento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_evento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 24730)
-- Name: tb_frequencia; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_frequencia (
    id bigint NOT NULL,
    datageracao date,
    totalhoraseventos integer,
    totalhorasmonitoria integer,
    usuario_id bigint
);


ALTER TABLE public.tb_frequencia OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 24729)
-- Name: tb_frequencia_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tb_frequencia ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_frequencia_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 24639)
-- Name: tb_funcionario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_funcionario (
    id bigint NOT NULL,
    cpf_funcionario character varying(255) NOT NULL,
    dta_funcionario character varying(255) NOT NULL,
    nome_funcionario character varying(255),
    num_funcionario character varying(255) NOT NULL,
    sexo_funcionario character varying(255) NOT NULL,
    cargo_id bigint,
    pagamento_id bigint,
    funcionarios_id bigint
);


ALTER TABLE public.tb_funcionario OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 24670)
-- Name: tb_funcionario_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.tb_funcionario_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.tb_funcionario_seq OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 24693)
-- Name: tb_monitoria; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_monitoria (
    id bigint NOT NULL,
    certificado character varying(255),
    datahora character varying(255),
    descricao character varying(255),
    titulo character varying(255),
    local character varying(255),
    usuariosistema_id bigint
);


ALTER TABLE public.tb_monitoria OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 24700)
-- Name: tb_monitoria_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.tb_monitoria_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.tb_monitoria_seq OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 24646)
-- Name: tb_ocorrencia_funcionario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_ocorrencia_funcionario (
    id bigint NOT NULL,
    data_ocorrencia character varying(255) NOT NULL,
    descricao character varying(255) NOT NULL,
    gravidade character varying(255) NOT NULL,
    responsavel_registro character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    tipo_ocorrencia character varying(255) NOT NULL
);


ALTER TABLE public.tb_ocorrencia_funcionario OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 24671)
-- Name: tb_ocorrencia_funcionario_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.tb_ocorrencia_funcionario_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.tb_ocorrencia_funcionario_seq OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 24653)
-- Name: tb_pagamento; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_pagamento (
    id bigint NOT NULL,
    data_pagamento character varying(255) NOT NULL,
    nome_cargo character varying(255) NOT NULL,
    tipo_pagamento character varying(255) NOT NULL,
    valor double precision NOT NULL
);


ALTER TABLE public.tb_pagamento OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 24672)
-- Name: tb_pagamento_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.tb_pagamento_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.tb_pagamento_seq OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 24660)
-- Name: tb_usuario_sistema; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_usuario_sistema (
    id bigint NOT NULL,
    login character varying(255) NOT NULL,
    nivel_acesso character varying(255) NOT NULL,
    senha character varying(255) NOT NULL,
    curso character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    nome character varying(255) NOT NULL,
    periodo_academico character varying(255) NOT NULL,
    ra character varying(255) NOT NULL,
    telefone character varying(255) NOT NULL
);


ALTER TABLE public.tb_usuario_sistema OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 24673)
-- Name: tb_usuario_sistema_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.tb_usuario_sistema_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.tb_usuario_sistema_seq OWNER TO postgres;

--
-- TOC entry 4997 (class 0 OID 24708)
-- Dependencies: 234
-- Data for Name: tb_avaliacao; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tb_avaliacao (id, data, nota, aluno_id, monitoria_id) FROM stdin;
1	2025-05-19	8	\N	\N
4	2025-05-19	9.5	53	53
\.


--
-- TOC entry 4980 (class 0 OID 24618)
-- Dependencies: 217
-- Data for Name: tb_cargo; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tb_cargo (id, contrato_trabalho, carga_horaria, departamento, descricao_cargo, nome_cargo) FROM stdin;
\.


--
-- TOC entry 4999 (class 0 OID 24714)
-- Dependencies: 236
-- Data for Name: tb_certificado; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tb_certificado (id, descricao, duracao, titulo, data, participante_id) FROM stdin;
\.


--
-- TOC entry 4981 (class 0 OID 24625)
-- Dependencies: 218
-- Data for Name: tb_contrato_trabalho; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tb_contrato_trabalho (id, data_fimm, data_inicio, salario_base, tipo_contrato) FROM stdin;
\.


--
-- TOC entry 4982 (class 0 OID 24632)
-- Dependencies: 219
-- Data for Name: tb_departamento; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tb_departamento (id, nome_departamento, ramal, responsavel) FROM stdin;
\.


--
-- TOC entry 5001 (class 0 OID 24722)
-- Dependencies: 238
-- Data for Name: tb_evento; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tb_evento (id, data, descricao, local, titulo) FROM stdin;
1	2025-09-15	Mostra de cursos do IFPR	IFPR - Auditório	Feira de Ciências
2	2025-10-20	Palestras e workshops sobre inovação e tecnologia.	IFPR - Bloco D, Sala D13	Semana da Tecnologia
3	2025-09-15	Mostra de projetos científicos dos alunos.	IFPR - Auditório	SEPIN
\.


--
-- TOC entry 5003 (class 0 OID 24730)
-- Dependencies: 240
-- Data for Name: tb_frequencia; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tb_frequencia (id, datageracao, totalhoraseventos, totalhorasmonitoria, usuario_id) FROM stdin;
1	2025-05-19	10	20	1
\.


--
-- TOC entry 4983 (class 0 OID 24639)
-- Dependencies: 220
-- Data for Name: tb_funcionario; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tb_funcionario (id, cpf_funcionario, dta_funcionario, nome_funcionario, num_funcionario, sexo_funcionario, cargo_id, pagamento_id, funcionarios_id) FROM stdin;
2	124789633371	14/09/1979	Ernesto	48988741236	M	\N	\N	\N
302	34567890112	14/05/1396	Valiati	45898636987	Masculino	\N	\N	\N
253	45698710000	17/04/1925	Lucas	78945612301	Masculino	\N	\N	\N
602	123.456.789-10	30/09/1998	Eduardo	46	M	\N	202	\N
\.


--
-- TOC entry 4994 (class 0 OID 24693)
-- Dependencies: 231
-- Data for Name: tb_monitoria; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tb_monitoria (id, certificado, datahora, descricao, titulo, local, usuariosistema_id) FROM stdin;
53	\N	2025-01-23	HTML,CSS E JS	Monitoria de WEB	IFPR	\N
102	\N	2025-03-25	Design Patterns	Monitoria de POO	IFPR	\N
\.


--
-- TOC entry 4984 (class 0 OID 24646)
-- Dependencies: 221
-- Data for Name: tb_ocorrencia_funcionario; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tb_ocorrencia_funcionario (id, data_ocorrencia, descricao, gravidade, responsavel_registro, status, tipo_ocorrencia) FROM stdin;
\.


--
-- TOC entry 4985 (class 0 OID 24653)
-- Dependencies: 222
-- Data for Name: tb_pagamento; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tb_pagamento (id, data_pagamento, nome_cargo, tipo_pagamento, valor) FROM stdin;
202	07-05-2025	Aux. Adm.	Depósito	2.5
\.


--
-- TOC entry 4986 (class 0 OID 24660)
-- Dependencies: 223
-- Data for Name: tb_usuario_sistema; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tb_usuario_sistema (id, login, nivel_acesso, senha, curso, email, nome, periodo_academico, ra, telefone) FROM stdin;
1	joao.monitor	MONITOR	senha123	Informática	joao@ifpr.edu.br	João Monitor	4º período	202512345	41999998888
102	carlos.tester	ADMIN	teste123	Sistemas de Informação	carlos@ifpr.edu.br	Carlos Tester	5º período	202599999	41988887777
53	ana.alterada	MONITOR	novaSenha	Informática	ana@ifpr.edu.br	Ana Alterada	6º período	202588888	41987776666
202	joao.silva	MONITOR	senha123	Sistemas de Informação	joao@ifpr.edu.br	João da Silva	5º período	123456	46999999999
1001	marcos	ALUNO	123	artes	joao.aluno@ifpr.edu.br	Marcos Aluno	1º período	20210001	41999990001
1004	simone	ADMIN	123	Informática	ana.admin@ifpr.edu.br	Simone Admin	N/A	20210004	41999990004
1002	luiz	MONITOR	123	Sistemas	maria.monitor@ifpr.edu.br	Luiz monitor	4º período	20210002	41999990002
1003	Marina	COORDENADOR	123	Informática	carlos.coord@ifpr.edu.br	Marina Coordenadora	N/A	20210003	41999990003
\.


--
-- TOC entry 5009 (class 0 OID 0)
-- Dependencies: 233
-- Name: tb_avaliacao_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tb_avaliacao_id_seq', 4, true);


--
-- TOC entry 5010 (class 0 OID 0)
-- Dependencies: 224
-- Name: tb_cargo_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tb_cargo_seq', 1, false);


--
-- TOC entry 5011 (class 0 OID 0)
-- Dependencies: 235
-- Name: tb_certificado_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tb_certificado_id_seq', 1, false);


--
-- TOC entry 5012 (class 0 OID 0)
-- Dependencies: 225
-- Name: tb_contrato_trabalho_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tb_contrato_trabalho_seq', 1, false);


--
-- TOC entry 5013 (class 0 OID 0)
-- Dependencies: 226
-- Name: tb_departamento_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tb_departamento_seq', 1, false);


--
-- TOC entry 5014 (class 0 OID 0)
-- Dependencies: 237
-- Name: tb_evento_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tb_evento_id_seq', 3, true);


--
-- TOC entry 5015 (class 0 OID 0)
-- Dependencies: 239
-- Name: tb_frequencia_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tb_frequencia_id_seq', 1, true);


--
-- TOC entry 5016 (class 0 OID 0)
-- Dependencies: 227
-- Name: tb_funcionario_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tb_funcionario_seq', 651, true);


--
-- TOC entry 5017 (class 0 OID 0)
-- Dependencies: 232
-- Name: tb_monitoria_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tb_monitoria_seq', 351, true);


--
-- TOC entry 5018 (class 0 OID 0)
-- Dependencies: 228
-- Name: tb_ocorrencia_funcionario_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tb_ocorrencia_funcionario_seq', 1, false);


--
-- TOC entry 5019 (class 0 OID 0)
-- Dependencies: 229
-- Name: tb_pagamento_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tb_pagamento_seq', 251, true);


--
-- TOC entry 5020 (class 0 OID 0)
-- Dependencies: 230
-- Name: tb_usuario_sistema_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tb_usuario_sistema_seq', 251, true);


--
-- TOC entry 4820 (class 2606 OID 24712)
-- Name: tb_avaliacao tb_avaliacao_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_avaliacao
    ADD CONSTRAINT tb_avaliacao_pkey PRIMARY KEY (id);


--
-- TOC entry 4798 (class 2606 OID 24624)
-- Name: tb_cargo tb_cargo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_cargo
    ADD CONSTRAINT tb_cargo_pkey PRIMARY KEY (id);


--
-- TOC entry 4822 (class 2606 OID 24720)
-- Name: tb_certificado tb_certificado_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_certificado
    ADD CONSTRAINT tb_certificado_pkey PRIMARY KEY (id);


--
-- TOC entry 4800 (class 2606 OID 24631)
-- Name: tb_contrato_trabalho tb_contrato_trabalho_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_contrato_trabalho
    ADD CONSTRAINT tb_contrato_trabalho_pkey PRIMARY KEY (id);


--
-- TOC entry 4802 (class 2606 OID 24638)
-- Name: tb_departamento tb_departamento_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_departamento
    ADD CONSTRAINT tb_departamento_pkey PRIMARY KEY (id);


--
-- TOC entry 4824 (class 2606 OID 24728)
-- Name: tb_evento tb_evento_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_evento
    ADD CONSTRAINT tb_evento_pkey PRIMARY KEY (id);


--
-- TOC entry 4826 (class 2606 OID 24734)
-- Name: tb_frequencia tb_frequencia_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_frequencia
    ADD CONSTRAINT tb_frequencia_pkey PRIMARY KEY (id);


--
-- TOC entry 4804 (class 2606 OID 24645)
-- Name: tb_funcionario tb_funcionario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_funcionario
    ADD CONSTRAINT tb_funcionario_pkey PRIMARY KEY (id);


--
-- TOC entry 4816 (class 2606 OID 24699)
-- Name: tb_monitoria tb_monitoria_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_monitoria
    ADD CONSTRAINT tb_monitoria_pkey PRIMARY KEY (id);


--
-- TOC entry 4808 (class 2606 OID 24652)
-- Name: tb_ocorrencia_funcionario tb_ocorrencia_funcionario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_ocorrencia_funcionario
    ADD CONSTRAINT tb_ocorrencia_funcionario_pkey PRIMARY KEY (id);


--
-- TOC entry 4810 (class 2606 OID 24659)
-- Name: tb_pagamento tb_pagamento_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_pagamento
    ADD CONSTRAINT tb_pagamento_pkey PRIMARY KEY (id);


--
-- TOC entry 4812 (class 2606 OID 24666)
-- Name: tb_usuario_sistema tb_usuario_sistema_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_usuario_sistema
    ADD CONSTRAINT tb_usuario_sistema_pkey PRIMARY KEY (id);


--
-- TOC entry 4806 (class 2606 OID 24680)
-- Name: tb_funcionario uk4g458xsbc1hwoosekmyol12fa; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_funcionario
    ADD CONSTRAINT uk4g458xsbc1hwoosekmyol12fa UNIQUE (pagamento_id);


--
-- TOC entry 4814 (class 2606 OID 24692)
-- Name: tb_usuario_sistema uk8k53acrae8gobxbl0kcwbvcd1; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_usuario_sistema
    ADD CONSTRAINT uk8k53acrae8gobxbl0kcwbvcd1 UNIQUE (ra);


--
-- TOC entry 4818 (class 2606 OID 24757)
-- Name: tb_monitoria ukcoe78bmqgk61fi72x2ub4fa9p; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_monitoria
    ADD CONSTRAINT ukcoe78bmqgk61fi72x2ub4fa9p UNIQUE (usuariosistema_id);


--
-- TOC entry 4830 (class 2606 OID 24758)
-- Name: tb_monitoria fk2e6py5si66olx09tux1fwmxul; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_monitoria
    ADD CONSTRAINT fk2e6py5si66olx09tux1fwmxul FOREIGN KEY (usuariosistema_id) REFERENCES public.tb_usuario_sistema(id);


--
-- TOC entry 4834 (class 2606 OID 24750)
-- Name: tb_frequencia fk5gstktksgd6cnrwtmebnfuv6b; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_frequencia
    ADD CONSTRAINT fk5gstktksgd6cnrwtmebnfuv6b FOREIGN KEY (usuario_id) REFERENCES public.tb_usuario_sistema(id);


--
-- TOC entry 4833 (class 2606 OID 24745)
-- Name: tb_certificado fkdajd0urjsuipuaa1sat81a5iw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_certificado
    ADD CONSTRAINT fkdajd0urjsuipuaa1sat81a5iw FOREIGN KEY (participante_id) REFERENCES public.tb_usuario_sistema(id);


--
-- TOC entry 4827 (class 2606 OID 24674)
-- Name: tb_funcionario fkeeocycgewyjbc4kytgy5jdudr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_funcionario
    ADD CONSTRAINT fkeeocycgewyjbc4kytgy5jdudr FOREIGN KEY (cargo_id) REFERENCES public.tb_cargo(id);


--
-- TOC entry 4831 (class 2606 OID 24735)
-- Name: tb_avaliacao fkkimvtd1grgkmbt6fmbdd1ve8e; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_avaliacao
    ADD CONSTRAINT fkkimvtd1grgkmbt6fmbdd1ve8e FOREIGN KEY (aluno_id) REFERENCES public.tb_usuario_sistema(id);


--
-- TOC entry 4832 (class 2606 OID 24740)
-- Name: tb_avaliacao fkq6k99fys8e439gjr7g7e5q357; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_avaliacao
    ADD CONSTRAINT fkq6k99fys8e439gjr7g7e5q357 FOREIGN KEY (monitoria_id) REFERENCES public.tb_monitoria(id);


--
-- TOC entry 4828 (class 2606 OID 24681)
-- Name: tb_funcionario fktbymo7ypqpg86qwdp6lhuvpgm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_funcionario
    ADD CONSTRAINT fktbymo7ypqpg86qwdp6lhuvpgm FOREIGN KEY (pagamento_id) REFERENCES public.tb_pagamento(id);


--
-- TOC entry 4829 (class 2606 OID 24686)
-- Name: tb_funcionario fkw4w75xs4m8l42gt01n798j5a; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_funcionario
    ADD CONSTRAINT fkw4w75xs4m8l42gt01n798j5a FOREIGN KEY (funcionarios_id) REFERENCES public.tb_cargo(id);


-- Completed on 2025-06-25 00:05:06

--
-- PostgreSQL database dump complete
--

